# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26828ad9f9de16907ee0243d14c82b797a08d97673230632fd14a6bdbe815cee3d7580b1fc00f8a8e2dbb7b3e5dbd094190ad8da19d870e2d65d572dc69d8ae5

test:
  secret_key_base: e09392ace5b5d759c329724e2b029f6e040a40783104477510485799e9ff78ca7e6df0c2bb52a8c10ea7a395be69f82422f2abe742aa85b602ff6931cdeab3fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
